# Generated by Django 3.2.7 on 2021-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=255),
        ),
    ]
