# Generated by Django 3.2.7 on 2021-09-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
